In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('adult.data',names=["age", "workClass", "fnlwgt", "education", "education-num",
           "marital-status", "occupation", "relationship", "race", "sex", 
           "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"])
df

age          workClass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workClass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loss    32561 non-null  int64 
 12  hours-per-week  32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [4]:
df.isna().sum().sum()

0

In [5]:
df.describe().T

count           mean            std      min       25%  \
age             32561.0      38.581647      13.640433     17.0      28.0   
fnlwgt          32561.0  189778.366512  105549.977697  12285.0  117827.0   
education-num   32561.0      10.080679       2.572720      1.0       9.0   
capital-gain    32561.0    1077.648844    7385.292085      0.0       0.0   
capital-loss    32561.0      87.303830     402.960219      0.0       0.0   
hours-per-week  32561.0      40.437456      12.347429      1.0      40.0   

                     50%       75%        max  
age                 37.0      48.0       90.0  
fnlwgt          178356.0  237051.0  1484705.0  
education-num       10.0      12.0       16.0  
capital-gain         0.0       0.0    99999.0  
capital-loss         0.0       0.0     4356.0  
hours-per-week      40.0      45.0       99.0

In [6]:
df['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [7]:
df = df.replace(' ?', np.nan)

In [8]:
df.isna().sum()

age                  0
workClass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [9]:
Nan_columns = ['workClass', 'occupation', 'native-country']

In [10]:
for col in Nan_columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [11]:
df.isna().sum().sum()

0

In [12]:
df.head()

age          workClass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [13]:
df['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder = LabelEncoder()

In [15]:
for column in df.columns:
    if df[column].dtypes == 'object':
        df[column] = LabelEncoder.fit_transform(df[column])

In [16]:
df['income'].value_counts()

0    24720
1     7841
Name: income, dtype: int64

In [17]:
X = df.drop('income', axis=1)
y = df['income']

In [18]:
X

age  workClass  fnlwgt  education  education-num  marital-status  \
0       39          6   77516          9             13               4   
1       50          5   83311          9             13               2   
2       38          3  215646         11              9               0   
3       53          3  234721          1              7               2   
4       28          3  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          3  257302          7             12               2   
32557   40          3  154374         11              9               2   
32558   58          3  151910         11              9               6   
32559   22          3  201490         11              9               4   
32560   52          4  287927         11              9               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               0             1     4    1          2174             0   
1               3             0     4    1             0             0   
2               5             1     4    1             0             0   
3               5             0     2    1             0             0   
4               9             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          12             5     4    0             0             0   
32557           6             0     4    1             0             0   
32558           0             4     4    0             0             0   
32559           0             3     4    1             0             0   
32560           3             5     4    0         15024             0   

       hours-per-week  native-country  
0                  40              38  
1                  13              38  
2                  40              38  
3                  40              38  
4                  40               4  
...               ...             ...  
32556              38              38  
32557              40              38  
32558              40              38  
32559              20              38  
32560              40              38  

[32561 rows x 14 columns]

In [19]:
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: income, Length: 32561, dtype: int32

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### BaggingClassifier

In [21]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier

In [22]:
bagging_clf = BaggingClassifier(base_estimator=SVC(),n_estimators=10, random_state=0)

In [23]:
bagging_clf.fit(X_train,y_train)

BaggingClassifier(base_estimator=SVC(), random_state=0)

In [24]:
bagging_clf_predict = bagging_clf.predict(X_test)

In [25]:
bagging_clf_predict

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,bagging_clf_predict)

0.7963893541782989

### Extra Tree Classifier

In [27]:
from sklearn.ensemble import ExtraTreesClassifier
ex_tree_clf = ExtraTreesClassifier(n_estimators=100, random_state=0)

In [28]:
ex_tree_clf.fit(X_train,y_train)

ExtraTreesClassifier(random_state=0)

In [29]:
ex_tree_clf_pred = ex_tree_clf.predict(X_test)

In [30]:
ex_tree_clf_pred

array([0, 0, 1, ..., 0, 0, 0])

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,ex_tree_clf_pred)

0.8464544946957008

### Voting Classifier

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
clf1 = LogisticRegression(multi_class='multinomial', random_state=1)
clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
clf3 = GaussianNB()

In [33]:
voting_clf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

In [34]:
voting_clf.fit(X_train,y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(multi_class='multinomial',
                                                 random_state=1)),
                             ('rf',
                              RandomForestClassifier(n_estimators=50,
                                                     random_state=1)),
                             ('gnb', GaussianNB())])

In [35]:
voting_clf_pred = voting_clf.predict(X_test)

In [36]:
voting_clf_pred

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,voting_clf_pred)

0.8116508468267262

### RandomForestClassifier

In [38]:
from sklearn.ensemble import RandomForestClassifier
RF_clf = RandomForestClassifier(max_depth=2, random_state=0)

In [39]:
RF_clf.fit(X_train,y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [41]:
RF_clf_pred = RF_clf.predict(X_test)

In [42]:
RF_clf_pred

array([0, 0, 0, ..., 0, 0, 0])

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,RF_clf_pred)

0.7981574539363484